name: Daily Helm Chart Sync

on:
  schedule:
    - cron: "0 3 * * *"  # 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Show target sources
        run: cat ./helm/sources.txt

      - name: Run Sync Script
        run: |
          ./helm/sync.sh
